server:
  port: 8110
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/srb_core?serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 12345
mybatis-plus:
  mapper-locations: classpath:wanho/core/admin/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl